### ISSUE TITLE
安裝時各文字的json檔並沒有安裝到

### ISSUE THREAD

**Issue by bestian** [g0v/react-zh-stroker#6]
我試著安裝並使用
但是
安裝時各文字的json檔並沒有安裝到
無法import

**Comment by caasi** [comment]
各文字的 json 可以從 https://github.com/g0v/zh-stroke-data 取得，或是待好心人也把它包裝成一個 npm package 。

**Comment by caasi** [comment]
在 https://github.com/g0v/zh-stroke-data 開 [issue][1] 了，先關閉此 issue 。

[1]: https://github.com/g0v/zh-stroke-data/issues/9

**Comment by caasi** [comment]
開好了： https://www.npmjs.com/package/zh-stroke-data
