### ISSUE TITLE
無法import { data, Word } from 'react-zh-stroker'

### ISSUE THREAD

**Issue by bestian** [g0v/react-zh-stroker#7]
import { data, Word } from 'react-zh-stroker'

has following error:

"export 'Word' was not found in 'react-zh-stroker'
"export 'data' was not found in 'react-zh-stroker'

**Comment by caasi** [comment]
這個我還不知道要怎麼修，因為 livescript 無法正確輸出 ES6 module ，請先改用：

```
import { default as RZS } from 'react-zh-stroker';
const { data, Word } = RZS;
```

等搞定完 livescript 輸出 ES6 module 的問題後再關掉。

**Comment by caasi** [comment]
先放棄輸出 ES module 格式的 js 檔，裝 v0.1.15 應可以正常 import 了
