### ISSUE TITLE
import時立即出現error

### ISSUE THREAD

**Issue by bestian** [g0v/react-zh-stroker#9]
i just write

import { default as RZS } from 'react-zh-stroker'

then got error like this:

 warning  in ./node_modules/Long/dist/Long.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!/Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/Long/dist/Long.js
    Used by 1 module(s), i. e.
    /Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!/Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/bytebuffer/dist/ByteBufferAB.js
* /Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!/Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/long/dist/Long.js
    Used by 1 module(s), i. e.
    /Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!/Users/tsung-haotang/Documents/GitHub/q-moedict/node_modules/bytebuffer/dist/ByteBufferAB.js

**Comment by caasi** [comment]
剛剛上了 v0.1.15 版，更新了造成這個問題的 bytebuffer 套件。你看看還有沒有這樣的問題？

**Comment by bestian** [comment]
瀏覽器的console出現新的error:

TypeError: Cannot read property 'g' of undefined
    at eval (index.js?ccf8:413)
    at createCommonjsModule (index.js?ccf8:17)
    at Object.eval (index.js?ccf8:409)
    at eval (index.js:688)
    at Object../node_modules/react-zh-stroker/dist/index.js

**Comment by caasi** [comment]
有公開的 repo 可以看嗎？也許下班後我可以看看

**Comment by bestian** [comment]
https://www.github.com/bestian/q-moeduct

**Comment by caasi** [comment]
測了一下，本來這個 repo 只支援到 React v15.5.0 以下的版本，但是 q-moedict 的 React 太新了。

剛剛發佈了可以在 React v16 之後使用的 react-zh-stroker v0.2.0 版，請試試看。

**Comment by bestian** [comment]
裝了新版之後，error沒了，但是筆劃只有畫出第一筆，不知為何 
可以幫測看看嗎？
https://www.github.com/bestian/q-moeduct

**Comment by caasi** [comment]
Word 只負責畫圖，需要動畫效果得自己不停更新 progress

**Comment by bestian** [comment]
可以寫進readme的demo嗎？

**Comment by caasi** [comment]
加好囉
